### ISSUE TITLE
Unexpected action when using Del key

### ISSUE THREAD

**Issue by TrustedSamurai** [ERROPiX/hydrogen-pack#5]
Hi,
Not a bug but more a user experience issue.  When you try to rename a div and then hit Del key while in the text edit section it deletes the element.  I've made a short video to show you.

http://somup.com/cYf3jvi0FV

Thanks for a great plugin.

John.

**Comment by ERROPiX** [comment]
@TrustedSamurai thanks for reporting this, I will try it locally and fix it

**Comment by TrustedSamurai** [comment]
Thank you. Did my video work ok?  Was it helpful?  I really have to talk less!  lol.

**Comment by ERROPiX** [comment]
I didn't know you were talking! sorry, but the video was without audio. can you send the original video or upload it to Vimeo or something better than somup like loom.com?

**Comment by TrustedSamurai** [comment]
Sorry.  My mic got turned off and I didn't even realise!
http://somup.com/cYf33biTKD

**Comment by ERROPiX** [comment]
The second issue has been fixed, but the first issue, not an issue. in Oxygen if you selected a div or section it is a container of other divs. but you copy a section, you can't add it to a div, so that's why.

Sometimes you want to copy a card and paste it in a div, it will be painful to have it pasted bellow it and then you have to drag. we can't satisfy both use case here, I guess probably I will add an exception so that if you were holding the shift key during paste, it will be added next to the active component instead of inside it

do you think this the best solution?

**Comment by TrustedSamurai** [comment]
Yes I understand what you mean.  When I review these actions again I
realise that I need to keep an eye on where the 'focus' is.  When I
selected the Section and pasted the div, the div appeared inside the
element with focus, the Section.  But then the focus shifted to the div.  I
didn't realise this.  So when I pasted again it pasted inside the div.
which is to be expected.  If i select the section again, it pastes the div
at the bottom of the section, which again is what I expect.  It's just that
I didn't see the focus had changed from section to div.  I think User
Experience could be improved here by keeping focus on Section where the
user selected.

What do you think?

John Anderson
*Forte Web Design*
ph: 0414 702 997

**Comment by ERROPiX** [comment]
> I think User Experience could be improved here by keeping focus on Section where the
user selected.

Yes, this can be an option, again, Oxygen does this by default, it moves to focus to newly inserted components, but it can be reverted if the user decide to do so because many user will paste the section and want it to be focused by default.

**Comment by ERROPiX** [comment]
@TrustedSamurai it's done locally

**Comment by ERROPiX** [comment]
Fixed in 1.0.3
