### ISSUE TITLE
Copy - Paste not working with Greek language selected

### ISSUE THREAD

**Issue by estraatios** [ERROPiX/hydrogen-pack#7]
Hi.

When I try to copy and paste across pages (keyboard shortcuts) it will work only if I have the English language selected. And I do not mean in the text or anything. I mean to select the language you want to write (next to the clock)

If I change to Greek I cannot copy and paste.

**Comment by ERROPiX** [comment]
@estraatios that's for explaining this, I thought you were talking about WordPress language, I will look at this

**Comment by estraatios** [comment]
Yes, I am talking about the computer input language. The one that you select to type. 

Not the WordPress language nor the content of the website language

**Comment by ERROPiX** [comment]
Ok, I understand the issue now, it's not about the copy-paste feature, it's about the shortcut.
Try this, set the language to Greek, copy the element using the right-click menu, and paste it somewhere. It will work fine.

The issue here is when you change the language, the character will no longer be **C** but something else depending on the language and keys combination.

**Comment by ERROPiX** [comment]
The new shortcuts manager solve the keyboard shortcuts issues
